feat(utils): enhance ,rm-pdf-password

diff --git a/dotfiles/.local/bin/,rm-pdf-password b/dotfiles/.local/bin/,rm-pdf-password
--- a/dotfiles/.local/bin/,rm-pdf-password
+++ b/dotfiles/.local/bin/,rm-pdf-password
@@ -1,10 +1,17 @@
 #!/usr/bin/bash
 #
 # Removes PDF password using qpdf utility (available via apt).
-set -e
+set -euo pipefail
 
 password=$1
 file=$2
 output="${file%.pdf}_decrypted.pdf"
 
-qpdf -password=$password -decrypt $file $output
+_have() { type "$1" &> /dev/null; }
+if _have qpdf; then
+  qpdf -password="$password" -decrypt "$file" "$output"
+  echo "$output saved"
+else
+  echo "'qpdf' not found. Aborting..."
+  exit 1
+fi
